---
- name: Systemd Test
  hosts: web
  become: true
  tasks:
#---------------------------------------------------------------------------------------------------
# Build nginx container
#---------------------------------------------------------------------------------------------------
  # Создание дирректории для сборки
  - name: create build directory
    file: 
      path: /root/dockerfiles
      state: directory
      owner: root 
      group: root
      mode: '0644'
  # Загрузка образа nginx
  - name: Pull nginx image
    community.docker.docker_image:
      name: nginx:latest
      source: pull
  # Копирование исходных файлов
  - name: copy source file on hosts
    template: 
      src: "{{ item }}"
      dest: /root/dockerfiles
      owner: root
      group: root
      mode: '0644'
    loop:
    - ./source-web/Dockerfile
    - ./source-web/index.html
  # Сборка образа контейнера
  - name: build container image
    docker_image:
      name: nginx_test:v1.0
      source: build
      build:
        path: /root/dockerfiles
      state: present
   # Запуск контейнера
  - name: run container
    docker_container: 
      name: nginx
      image: nginx_test:v1.0
      published_ports:
      - "8080:80"