services:
  nginx:
    image: nginx:1.10.1-alpine
    container_name: my-nginx
    volumes:
      - ./configs/html/index.html:/usr/share/nginx/html/index.html  # Только ваш файл
      - ./logs:/var/log/nginx
    ports:
      - "8080:80"
    restart: unless-stopped